
GET http://localhost:5050/posts HTTP/1.1
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmNvY29saWEzMzBAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiTWFyY28iLCJsYXN0TmFtZSI6IkNvbGlhIiwicm9sZSI6InVzZXIiLCJhZ2UiOjM5LCJpZCI6IjY0NzczZTYzNWY1Njg3YjVlM2Q0ZTAwMCIsImlhdCI6MTY4NjU1NDYyNSwiZXhwIjoxNjg2NjQxMDI1fQ.BGTGloS71FoTEb-Xcrkg3jOwKqfIxE2D3m9_pN_tZ9U

######

GET http://localhost:5050/posts/4 HTTP/1.1
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmNvY29saWEzMzBAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiTWFyY28iLCJsYXN0TmFtZSI6IkNvbGlhIiwicm9sZSI6InVzZXIiLCJhZ2UiOjM5LCJpZCI6IjY0NzczZTYzNWY1Njg3YjVlM2Q0ZTAwMCIsImlhdCI6MTY4NjU1NDYyNSwiZXhwIjoxNjg2NjQxMDI1fQ.BGTGloS71FoTEb-Xcrkg3jOwKqfIxE2D3m9_pN_tZ9U

######

POST http://localhost:5050/posts HTTP/1.1
content-type: application/json

{
    "title": "post referenziato 565453",
    "content": "Lorem ipsum post referenziato",
    "author": "64773e635f5687b5e3d4e000", 
    "rate": 3
}

######

PATCH  http://localhost:5050/posts/64770707f58045f6db33675b HTTP/1.1
content-type: application/json

{
    "title": "Titolo modificato",
    "content": "Lorem ipsum modificato",
    "author": "Gianluca Cobucci modificato", 
    "rate": 3
}


#####

DELETE  http://localhost:5050/posts/64770707f58045f6db33675b HTTP/1.1

#####