
POST http://localhost:5050/sendMail HTTP/1.1
content-type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmNvY29saWEzMzBAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiTWFyY28iLCJsYXN0TmFtZSI6IkNvbGlhIiwicm9sZSI6InVzZXIiLCJhZ2UiOjM5LCJpZCI6IjY0NzczZTYzNWY1Njg3YjVlM2Q0ZTAwMCIsImlhdCI6MTY4NjU1NDYyNSwiZXhwIjoxNjg2NjQxMDI1fQ.BGTGloS71FoTEb-Xcrkg3jOwKqfIxE2D3m9_pN_tZ9U

{
    "subject": "hello from nodemailer",
    "message": "prima mail con nodemailer"
}